protocols = imap lmtp
listen = *

mail_home = /var/mail/vhosts/%d/%n
mail_location = maildir:/var/mail/vhosts/%d/%n
mail_privileged_group = mail

ssl = required
ssl_cert = </etc/letsencrypt/live/mail.yourmailplatform.com/fullchain.pem
ssl_key = </etc/letsencrypt/live/mail.yourmailplatform.com/privkey.pem

auth_mechanisms = plain login
disable_plaintext_auth = yes

passdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}

userdb {
  driver = static
  args = uid=vmail gid=vmail home=/var/mail/vhosts/%d/%n
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}
